/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/analyses/follow-up": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analysis Follow Up */
        post: operations["analysis_follow_up_api_v1_analyses_follow_up_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analyses/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analysis Report */
        post: operations["analysis_report_api_v1_analyses_report_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live */
        get: operations["live_api_v1_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_api_v1_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Meta */
        get: operations["meta_api_v1_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profiles/calculate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Calculate */
        post: operations["calculate_api_v1_profiles_calculate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/analyses/follow-up": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analysis Follow Up V2 */
        post: operations["analysis_follow_up_v2_api_v2_analyses_follow_up_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/analyses/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analysis Report V2 */
        post: operations["analysis_report_v2_api_v2_analyses_report_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Meta V2 */
        get: operations["meta_v2_api_v2_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/profiles/calculate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Calculate V2 */
        post: operations["calculate_v2_api_v2_profiles_calculate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalysisClaim */
        AnalysisClaim: {
            /** Calculation Ref */
            calculation_ref: string;
            claim_type: components["schemas"]["ClaimType"];
            /** Composer Rule Id */
            composer_rule_id?: string | null;
            /** Counter Hypothesis */
            counter_hypothesis?: string | null;
            /** Knowledge Ref */
            knowledge_ref: string;
            /** Number */
            number: number;
            /** Text */
            text: string;
            /** Uncertainty */
            uncertainty?: string | null;
        };
        /**
         * AnalysisFollowUp
         * @description Canonical v2 follow-up — the only structure newly produced by the agent.
         */
        AnalysisFollowUp: {
            /** Answer */
            answer: string;
            /** Claims */
            claims: components["schemas"]["AnalysisClaim"][];
            /** Limitations */
            limitations: string[];
            provenance: components["schemas"]["AnalysisProvenance"];
            /**
             * Schema Version
             * @default analysis-follow-up-v2
             * @constant
             */
            schema_version: "analysis-follow-up-v2";
        };
        /** AnalysisFollowUpRequest */
        AnalysisFollowUpRequest: {
            /**
             * Consent
             * @constant
             */
            consent: true;
            /** Device Id */
            device_id: string;
            /** Profile */
            profile: components["schemas"]["ProfileCalculationResult"] | components["schemas"]["LegacyV2ProfileCalculationResult"];
            /** Question */
            question: string;
            report: components["schemas"]["AnalysisReport"];
        };
        /**
         * AnalysisFollowUpRequestV2
         * @description V2 follow-up request — re-validates the V4 profile and the signed report.
         */
        AnalysisFollowUpRequestV2: {
            /**
             * Consent
             * @constant
             */
            consent: true;
            /** Device Id */
            device_id: string;
            profile: components["schemas"]["ProfileCalculationResultV4"];
            /** Question */
            question: string;
            report: components["schemas"]["AnalysisReportV3"];
        };
        /** AnalysisFollowUpV3 */
        AnalysisFollowUpV3: {
            /** Answer */
            answer: string;
            /** Claims */
            claims: components["schemas"]["ClaimV3"][];
            /** Context Signature */
            context_signature: string;
            /**
             * Follow Up Id
             * Format: uuid
             */
            follow_up_id: string;
            /** Limitations */
            limitations: string[];
            provenance: components["schemas"]["AnalysisProvenanceV3"];
            /**
             * Report Id
             * Format: uuid
             */
            report_id: string;
            /**
             * Schema Version
             * @default analysis-follow-up-v3
             * @constant
             */
            schema_version: "analysis-follow-up-v3";
        };
        /**
         * AnalysisProvenance
         * @description Provenance shared by v1 (read) and v2 (write) reports.
         *
         *     ``temperature``/``top_p`` are nullable because the DeepSeek thinking mode
         *     renders them ineffective (provider-managed sampling). Legacy v1 data with
         *     concrete floats validates unchanged against this superset.
         */
        AnalysisProvenance: {
            /** Calculation Hash */
            calculation_hash: string;
            /** Completion Tokens */
            completion_tokens: number;
            /** Context Signature */
            context_signature: string;
            /**
             * Effective Sampling
             * @default provider_managed
             * @constant
             */
            effective_sampling: "provider_managed";
            /** Knowledge Bundle */
            knowledge_bundle: string;
            /** Model */
            model: string;
            /** Prompt Tokens */
            prompt_tokens: number;
            /** Prompt Version */
            prompt_version: string;
            /** Provider */
            provider: string;
            /** Provider Fingerprint */
            provider_fingerprint: string | null;
            /**
             * Reasoning Effort
             * @default high
             * @constant
             */
            reasoning_effort: "high";
            /** Temperature */
            temperature?: number | null;
            /** Thinking */
            thinking: string;
            /** Top P */
            top_p?: number | null;
        };
        /** AnalysisProvenanceV3 */
        AnalysisProvenanceV3: {
            /** Calculation Hash */
            calculation_hash: string;
            /** Completion Tokens */
            completion_tokens: number;
            /** Context Signature */
            context_signature: string;
            /**
             * Effective Sampling
             * @default provider_managed
             * @constant
             */
            effective_sampling: "provider_managed";
            /** Knowledge Bundle */
            knowledge_bundle: string;
            /** Model */
            model: string;
            /** Prompt Tokens */
            prompt_tokens: number;
            /** Prompt Version */
            prompt_version: string;
            /** Provider */
            provider: string;
            /** Provider Fingerprint */
            provider_fingerprint?: string | null;
            /**
             * Reasoning Effort
             * @default high
             * @constant
             */
            reasoning_effort: "high";
            /**
             * Thinking
             * @default enabled
             */
            thinking: string;
        };
        /**
         * AnalysisReport
         * @description Canonical v2 report — the only structure newly produced by the agent.
         */
        AnalysisReport: {
            /** Limitations */
            limitations: string[];
            provenance: components["schemas"]["AnalysisProvenance"];
            /**
             * Schema Version
             * @default analysis-report-v2
             * @constant
             */
            schema_version: "analysis-report-v2";
            /** Sections */
            sections: components["schemas"]["AnalysisSection"][];
            /** Suggestions */
            suggestions: string[];
            /** Summary */
            summary: string;
        };
        /** AnalysisReportContentV3 */
        AnalysisReportContentV3: {
            /**
             * Global Limitations
             * @default []
             */
            global_limitations: string[];
            /** Sections */
            sections: components["schemas"]["AnalysisSectionV3"][];
            /** Summary */
            summary: string;
        };
        /** AnalysisReportRequest */
        AnalysisReportRequest: {
            /**
             * Consent
             * @constant
             */
            consent: true;
            /** Device Id */
            device_id: string;
            /** Profile */
            profile: components["schemas"]["ProfileCalculationResult"] | components["schemas"]["LegacyV2ProfileCalculationResult"];
        };
        /**
         * AnalysisReportRequestV2
         * @description V2 report request — carries the canonical V4 profile for re-validation.
         */
        AnalysisReportRequestV2: {
            /**
             * Consent
             * @constant
             */
            consent: true;
            /** Device Id */
            device_id: string;
            profile: components["schemas"]["ProfileCalculationResultV4"];
        };
        /** AnalysisReportV3 */
        AnalysisReportV3: {
            content: components["schemas"]["AnalysisReportContentV3"];
            /** Context Signature */
            context_signature: string;
            /** Generation Context Hash */
            generation_context_hash: string;
            provenance: components["schemas"]["AnalysisProvenanceV3"];
            /** Report Content Hash */
            report_content_hash: string;
            /**
             * Report Id
             * Format: uuid
             */
            report_id: string;
            /**
             * Schema Version
             * @default analysis-report-v3
             * @constant
             */
            schema_version: "analysis-report-v3";
        };
        /** AnalysisSection */
        AnalysisSection: {
            /** Claims */
            claims: components["schemas"]["AnalysisClaim"][];
            /** Title */
            title: string;
        };
        /** AnalysisSectionV3 */
        AnalysisSectionV3: {
            /**
             * Applicable
             * @default true
             */
            applicable: boolean;
            /**
             * Claims
             * @default []
             */
            claims: components["schemas"]["ClaimV3"][];
            /**
             * Counter Hypotheses
             * @default []
             */
            counter_hypotheses: string[];
            /**
             * Limitations
             * @default []
             */
            limitations: string[];
            /** Model Heading */
            model_heading?: string | null;
            /**
             * Practical Options
             * @default []
             */
            practical_options: string[];
            /**
             * Reflection Questions
             * @default []
             */
            reflection_questions: string[];
            /** Section Id */
            section_id: string;
            /** Summary */
            summary: string;
            /**
             * Supporting Calculation Refs
             * @default []
             */
            supporting_calculation_refs: string[];
            /**
             * Supporting Knowledge Refs
             * @default []
             */
            supporting_knowledge_refs: string[];
        };
        /**
         * AuditTrace
         * @description Deterministic audit trail attached to every calculation result.
         *
         *     The trace is one component of the CalculationHashEnvelope.
         *     The calculation hash also covers the schema version, relevant input
         *     fields, MethodPolicy and calculated results — not the trace alone.
         */
        AuditTrace: {
            /** Calculation Steps */
            calculation_steps?: components["schemas"]["CalculationStep"][];
            /**
             * Disambiguation Required
             * @description True iff an ambiguous Y (ADR 0001) or other ambiguity was hit.
             * @default false
             */
            disambiguation_required: boolean;
            /** Normalization Steps */
            normalization_steps?: components["schemas"]["NormalizationStep"][];
            /** Warnings */
            warnings?: string[];
        };
        /**
         * CalculationStep
         * @description A single auditable step in a calculation (Master Contract §6.3).
         *
         *     The deterministic hash of a result is computed over the sorted JSON of
         *     its steps, so every step must carry exactly the fields that influence
         *     the outcome - nothing more, nothing less.
         */
        CalculationStep: {
            /**
             * Inputs
             * @description Numeric inputs consumed by this step, in order.
             */
            inputs?: number[];
            /**
             * Label
             * @description Human-readable step identifier (stable).
             */
            label: string;
            /**
             * Note
             * @description Optional deterministic note (no free text logic).
             * @default
             */
            note: string;
            /**
             * Output
             * @description Numeric output produced by this step.
             */
            output: number;
        };
        /**
         * ClaimType
         * @description Statement classes (Master Contract §2.2).
         *
         *     Every artifact in the system is tagged with exactly one claim type so
         *     that symbolic tradition, deterministic calculation, interpretive
         *     hypothesis and empirical evidence can never be silently conflated.
         * @enum {string}
         */
        ClaimType: "input_fact" | "calculation_fact" | "traditional_claim" | "interpretive_hypothesis" | "empirical_evidence" | "practical_suggestion";
        /** ClaimV3 */
        ClaimV3: {
            /**
             * Calculation Refs
             * @default []
             */
            calculation_refs: string[];
            /** Claim Id */
            claim_id: string;
            /** @default interpretive_hypothesis */
            claim_type: components["schemas"]["ClaimType"];
            /** Composer Rule Id */
            composer_rule_id?: string | null;
            /**
             * Knowledge Refs
             * @default []
             */
            knowledge_refs: string[];
            /** Text */
            text: string;
            /** Uncertainty */
            uncertainty?: string | null;
        };
        /**
         * ConsistencyStatus
         * @description A-vs-B consistency report (Master Contract §3.2).
         */
        ConsistencyStatus: {
            /** A Equals B */
            a_equals_b: boolean;
            /** Life Path A */
            life_path_a: number;
            /** Life Path B */
            life_path_b: number;
            /**
             * Warning
             * @description Empty when A == B.
             * @default
             */
            warning: string;
        };
        /**
         * CycleCalculationResult
         * @description Personal date cycles and the four lifetime Pinnacle/Challenge phases.
         */
        CycleCalculationResult: {
            /**
             * As Of Date
             * Format: date
             */
            as_of_date: string;
            /** Challenges */
            challenges: components["schemas"]["CyclePhase"][];
            personal_day: components["schemas"]["NumberResult"];
            personal_month: components["schemas"]["NumberResult"];
            personal_year: components["schemas"]["NumberResult"];
            /** Pinnacles */
            pinnacles: components["schemas"]["CyclePhase"][];
        };
        /**
         * CycleCalculationResultV2
         * @description Personal date cycles using V2 NumberModel and corrected formulas (PR #19).
         */
        CycleCalculationResultV2: {
            /**
             * As Of Date
             * Format: date
             */
            as_of_date: string;
            /** Challenges */
            challenges: components["schemas"]["NumberModel"][];
            personal_day: components["schemas"]["NumberModel"];
            personal_month: components["schemas"]["NumberModel"];
            personal_year: components["schemas"]["NumberModel"];
            /** Pinnacles */
            pinnacles: components["schemas"]["NumberModel"][];
        };
        /**
         * CyclePhase
         * @description One numbered Pinnacle or Challenge phase with inclusive age boundaries.
         */
        CyclePhase: {
            /** End Age */
            end_age?: number | null;
            number: components["schemas"]["NumberResult"];
            /** Ordinal */
            ordinal: number;
            /** Start Age */
            start_age: number;
        };
        /**
         * DateMethod
         * @description Life Path reduction strategy.
         *
         *     ``BOTH`` runs A and B and emits a consistency warning when they
         *     diverge (Master Contract §3.2, V1 minimal scope).
         * @enum {string}
         */
        DateMethod: "sum_all_digits" | "component_then_sum" | "both";
        /** FieldError */
        FieldError: {
            /** Code */
            code: string;
            /** Field */
            field: string;
            /** Message */
            message: string;
        };
        /**
         * KarmicDebtInfo
         * @description Methodically defined karmic debt number with its origin (Korrektur 1).
         *
         *     The marker is attached ONLY when the *unreduced core value* of a Life
         *     Path method (the raw total before the first reduction step) is one of
         *     {13, 14, 16, 19}. Random intermediate sums are NOT karmic markers.
         *     ``origin`` records which methodical component produced the value, e.g.
         *     ``'total_sum'`` (Life Path A) or ``'component_sum'`` (Life Path B).
         */
        KarmicDebtInfo: {
            /**
             * Number
             * @description Karmic debt number (13, 14, 16 or 19).
             */
            number: number;
            /**
             * Origin
             * @description Methodical component that produced the value (e.g. 'total_sum').
             */
            origin: string;
        };
        /**
         * KarmicOccurrence
         * @description A karmic debt value found during reduction with its precise origin type.
         *
         *     origin_type distinguishes three cases (PR #19):
         *     * ``direct_raw`` — the methodically defined raw total itself is karmic
         *       (e.g. birthday=16).
         *     * ``reduction_intermediate`` — a karmic number appears as an intermediate
         *       step in the chain (e.g. expression 59→14→5).
         *     * ``component_total`` — the sum of reduced components is karmic
         *       (e.g. Life Path B component sum = 13).
         */
        KarmicOccurrence: {
            /**
             * Origin Type
             * @description direct_raw | reduction_intermediate | component_total
             */
            origin_type: string;
            /**
             * Value
             * @description Karmic debt number (13, 14, 16 or 19).
             */
            value: number;
        };
        /**
         * LegacyV2NameNumberSet
         * @description Historical V2 name contract, accepted only for server-side recalculation.
         */
        LegacyV2NameNumberSet: {
            /** Basis */
            basis: string;
            expression: components["schemas"]["NumberResult"];
            /** Normalized Name */
            normalized_name: string;
            /** Original Name */
            original_name: string;
            personality: components["schemas"]["NumberResult"];
            /** Segments */
            segments: components["schemas"]["NameSegmentResult"][];
            soul_urge: components["schemas"]["NumberResult"];
            /**
             * Variants
             * @default []
             */
            variants: components["schemas"]["NameNumberVariant"][];
            /**
             * Y Classifications
             * @default []
             */
            y_classifications: string[];
        };
        /**
         * LegacyV2ProfileCalculationResult
         * @description Read-only V2 envelope; calculated fields are never trusted by the API.
         */
        LegacyV2ProfileCalculationResult: {
            active_name?: components["schemas"]["LegacyV2NameNumberSet"] | null;
            attitude: components["schemas"]["NumberResult"];
            birthday: components["schemas"]["NumberResult"];
            /** @default calculation_fact */
            claim_type: components["schemas"]["ClaimType"];
            consistency: components["schemas"]["ConsistencyStatus"];
            core_name?: components["schemas"]["LegacyV2NameNumberSet"] | null;
            cycles: components["schemas"]["CycleCalculationResult"];
            /** Deterministic Hash */
            deterministic_hash: string;
            input_ref: components["schemas"]["PersonInput"];
            life_path_a: components["schemas"]["LifePathResult"];
            life_path_b: components["schemas"]["LifePathResult"];
            maturity: components["schemas"]["NumberResult"];
            /**
             * Name
             * @default complete_profile
             */
            name: string;
            policy: components["schemas"]["MethodPolicy"];
            /**
             * Schema Version
             * @constant
             */
            schema_version: "profile-calculation-result-v2";
            trace: components["schemas"]["AuditTrace"];
        };
        /**
         * LifePathResult
         * @description Life Path result for one reduction method (A or B).
         *
         *     Carries the *methodically defined unreduced core value* (``raw_total``)
         *     alongside the final reduced value, the slash-notation reduction path
         *     (``compound_notation``) and an optional karmic-debt marker attached to
         *     that raw total (Korrektur 1).
         */
        LifePathResult: {
            /**
             * Components
             * @description Per-component reductions (only for method B).
             */
            components?: {
                [key: string]: number;
            };
            /**
             * Compound Notation
             * @description Reduction path as slash-notation, e.g. '19/10/1' or '37/10/1'.
             */
            compound_notation: string;
            /** @description Karmic debt info iff raw_total is a karmic debt number, else None. */
            karmic_debt?: components["schemas"]["KarmicDebtInfo"] | null;
            /**
             * Method
             * @description 'sum_all_digits' (A) or 'component_then_sum' (B).
             */
            method: string;
            /**
             * Raw Total
             * @description Methodically defined unreduced core value before the first reduction.
             */
            raw_total: number;
            /**
             * Reduced Value
             * @description Final reduced value (1-9 or a master number); mirrors reduction.value.
             */
            reduced_value: number;
            reduction: components["schemas"]["ReductionOutcome"];
            /**
             * Steps
             * @description Ordered audit steps for this method.
             */
            steps?: components["schemas"]["CalculationStep"][];
        };
        /** LiveStatus */
        LiveStatus: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
        };
        /** LlmMeta */
        LlmMeta: {
            /**
             * Enabled
             * @default false
             */
            enabled: boolean;
            /** Provider */
            provider?: string | null;
        };
        /**
         * Locale
         * @description Locale for normalization policy selection.
         *
         *     V1 ships only ``DE``; other locales are extension points.
         * @enum {string}
         */
        Locale: "de" | "en";
        /** MetaResponse */
        MetaResponse: {
            /**
             * Api Version
             * @default v1
             * @constant
             */
            api_version: "v1";
            /** Knowledge Bundle */
            knowledge_bundle: string;
            llm?: components["schemas"]["LlmMeta"];
            /**
             * Method System
             * @default pythagorean
             * @constant
             */
            method_system: "pythagorean";
            /**
             * Method Version
             * @default v1
             * @constant
             */
            method_version: "v1";
            /** Package Version */
            package_version: string;
            /** Profile Schema Version */
            profile_schema_version: string;
        };
        /**
         * MetaResponseV2
         * @description Capability contract for the /api/v2 endpoint family.
         */
        MetaResponseV2: {
            /**
             * Api Version
             * @default v2
             * @constant
             */
            api_version: "v2";
            /**
             * Endpoint Method Version
             * @default v2
             * @constant
             */
            endpoint_method_version: "v2";
            llm?: components["schemas"]["LlmMeta"];
            /**
             * Package Version
             * @default
             */
            package_version: string;
            /**
             * Product Default Method Version
             * @default v1
             * @enum {string}
             */
            product_default_method_version: "v1" | "v2";
            /**
             * Rollout Stage
             * @default disabled
             * @enum {string}
             */
            rollout_stage: "disabled" | "opt_in" | "canary" | "default";
            /**
             * Supported Knowledge Bundles
             * @default []
             */
            supported_knowledge_bundles: string[];
            /**
             * Supported Method Versions
             * @default [
             *       "v2"
             *     ]
             */
            supported_method_versions: "v2"[];
            /**
             * Supported Profile Schema Versions
             * @default []
             */
            supported_profile_schema_versions: string[];
            /**
             * Supported Report Schema Versions
             * @default []
             */
            supported_report_schema_versions: string[];
        };
        /**
         * MethodPolicy
         * @description Explicit method configuration (Master Contract §6.2).
         *
         *     No silent defaults: every policy dimension relevant to 0.1.0 is an
         *     explicit field with a documented canonical default. Mixing
         *     incompatible policies (e.g. two umlaut policies) is rejected.
         */
        MethodPolicy: {
            /**
             * @description Life Path A/B selection (Master Contract §3.2).
             * @default both
             */
            date_method: components["schemas"]["DateMethod"];
            /**
             * @description Normalization locale.
             * @default de
             */
            locale: components["schemas"]["Locale"];
            /**
             * Master Numbers
             * @description Numbers held as-is during reduction.
             * @default [
             *       11,
             *       22,
             *       33
             *     ]
             */
            master_numbers: number[];
            /**
             * @description core_name vs active_name selection (ADR 0004).
             * @default both_separate
             */
            name_basis: components["schemas"]["NameBasis"];
            /** @default pythagorean */
            system: components["schemas"]["MethodSystem"];
            /**
             * @description Umlaut/accent normalization (ADR 0002).
             * @default de-direct-v1
             */
            umlaut_policy: components["schemas"]["UmlautPolicy"];
            /**
             * Version
             * @description Method version tag.
             * @default v1
             */
            version: string;
            /**
             * @description Y classification (ADR 0001).
             * @default phonetic
             */
            y_mode: components["schemas"]["YMode"];
        };
        /**
         * MethodSystem
         * @description Numerological method systems.
         *
         *     V1 implements only ``PYTHAGOREAN``. Other systems are documented
         *     extension points (Master Contract §3.1) and must never be silently
         *     mixed (calculation-engineer agent contract §4).
         * @enum {string}
         */
        MethodSystem: "pythagorean" | "chaldean" | "kabbalistic";
        /**
         * NameBasis
         * @description Two-level name model selector (ADR 0004).
         *
         *     There is intentionally no ``MIXED`` or ``WEIGHTED`` value: silently
         *     fusing ``core_name`` and ``active_name`` would violate the statement
         *     class separation (Master Contract §2.2).
         * @enum {string}
         */
        NameBasis: "core_name_only" | "active_name_only" | "both_separate";
        /**
         * NameNumberSet
         * @description All name-derived values for one explicitly separated name profile.
         */
        NameNumberSet: {
            /** Basis */
            basis: string;
            expression: components["schemas"]["NumberResult"];
            maturity: components["schemas"]["NumberResult"];
            /** Normalized Name */
            normalized_name: string;
            /** Original Name */
            original_name: string;
            personality: components["schemas"]["NumberResult"];
            /** Segments */
            segments: components["schemas"]["NameSegmentResult"][];
            soul_urge: components["schemas"]["NumberResult"];
            /** Variants */
            variants?: components["schemas"]["NameNumberVariant"][];
            /** Y Classifications */
            y_classifications?: string[];
        };
        /**
         * NameNumberSetV2
         * @description Name-derived numbers using the V2 NumberModel (pythagorean-v2).
         */
        NameNumberSetV2: {
            /** Basis */
            basis: string;
            expression: components["schemas"]["NumberModel"];
            maturity: components["schemas"]["NumberModel"];
            /** Normalized Name */
            normalized_name: string;
            /** Original Name */
            original_name: string;
            personality: components["schemas"]["NumberModel"];
            soul_urge: components["schemas"]["NumberModel"];
            /** Y Classifications */
            y_classifications?: string[];
        };
        /**
         * NameNumberVariant
         * @description A complete vowel/consonant result for one explicit Y interpretation.
         */
        NameNumberVariant: {
            expression: components["schemas"]["NumberResult"];
            /** Label */
            label: string;
            personality: components["schemas"]["NumberResult"];
            soul_urge: components["schemas"]["NumberResult"];
        };
        /**
         * NameSegmentResult
         * @description Auditable subtotal for one whitespace- or hyphen-delimited name segment.
         */
        NameSegmentResult: {
            /** Compound Notation */
            compound_notation: string;
            /** Raw Total */
            raw_total: number;
            /** Reduced Value */
            reduced_value: number;
            /** Text */
            text: string;
        };
        /**
         * NormalizationStep
         * @description A single normalization transformation (ADR 0002 §6).
         */
        NormalizationStep: {
            /**
             * Input
             * @description Input string before the transformation.
             */
            input: string;
            /**
             * Note
             * @description Optional deterministic note.
             * @default
             */
            note: string;
            /**
             * Output
             * @description Output string after the transformation.
             */
            output: string;
            /**
             * Step
             * @description Stable step identifier (e.g. 'unicode_nfc').
             */
            step: string;
        };
        /**
         * NumberModel
         * @description Rich V2 numeric model (PR #19) with full reduction chain, karmic origin
         *     differentiation, and master-number / compound classification.
         *
         *     Replaces ``NumberResult`` for pythagorean-v2 code paths.  The two models
         *     coexist; pythagorean-v1 still uses ``NumberResult``.
         *
         *     Key invariants:
         *     * ``root_value`` is ALWAYS in 1..9 (the final single-digit result).
         *     * ``held_master_value`` is ``None`` unless the chain passes through 11/22/33.
         *     * ``is_master`` is ``True`` iff ``held_master_value is not None``.
         *     * 44 is NOT a master number (``is_master=False`` for raw_total=44).
         *     * ``reduction_chain`` always ends at ``root_value`` (including past masters).
         *     * ``display_notation`` renders the chain as slash-notation.
         */
        NumberModel: {
            /**
             * Components
             * @description Original summation components before the raw_total.
             */
            components?: number[];
            /**
             * Compound Classification
             * @description master_number | karmic_debt | compound | None.
             */
            compound_classification?: string | null;
            /**
             * Display Notation
             * @description Slash notation, e.g. '29/11/2', '40/4', '22/4'.
             */
            display_notation: string;
            /**
             * Held Master Value
             * @description Master number in chain (11/22/33) or None.
             */
            held_master_value?: number | null;
            /**
             * Is Master
             * @description True only when held_master_value is not None (11/22/33; NOT 44).
             * @default false
             */
            is_master: boolean;
            /**
             * Karmic Occurrences
             * @description Karmic debt hits in this reduction, with origin context.
             */
            karmic_occurrences?: components["schemas"]["KarmicOccurrence"][];
            /** Raw Total */
            raw_total: number;
            /**
             * Reduction Chain
             * @description Full chain from raw_total to root_value, e.g. (29,11,2).
             */
            reduction_chain: number[];
            /**
             * Root Value
             * @description Final 0-9 result (0 only for challenge=0).
             */
            root_value: number;
            /**
             * Steps
             * @description Human-readable calculation steps for the audit trail.
             */
            steps?: string[];
        };
        /**
         * NumberResult
         * @description One deterministic numerological value with a reproducible reduction path.
         */
        NumberResult: {
            /** Components */
            components?: {
                [key: string]: number;
            };
            /** Compound Notation */
            compound_notation: string;
            /**
             * Is Master
             * @default false
             */
            is_master: boolean;
            /** Name */
            name: string;
            /** Raw Total */
            raw_total: number;
            /** Reduced Value */
            reduced_value: number;
            /** Steps */
            steps?: components["schemas"]["CalculationStep"][];
        };
        /**
         * PersonInput
         * @description Person input contract (Master Contract §6.1).
         *
         *     The Walking Skeleton (0.1.0) only consumes ``core_name`` and
         *     ``birth_date`` for the Life Path calculation, but the full contract is
         *     modelled here so later name-based numbers (Expression, Soul Urge,
         *     Personality, Maturity - Phase 4+) can reuse the same input without a
         *     breaking migration.
         *
         *     * ``core_name`` - full birth name (authoritative for the core profile,
         *       ADR 0004 §1). Required.
         *     * ``active_name`` - currently used name, optional. When present and
         *       different from ``core_name`` it triggers the supplementary profile
         *       (ADR 0004 §2). Never silently merged with ``core_name``.
         *     * ``birth_date`` - calendar date of birth. The Life Path A/B
         *       calculations operate exclusively on this field.
         *     * ``as_of_date`` - explicit evaluation date for deterministic tests.
         *       MUST be >= ``birth_date`` for a person profile (Korrektur 3); the
         *       domain core never calls ``date.today()`` - the CLI defaults this at
         *       its own boundary (Korrektur 2). General date analysis (later) will
         *       not carry this constraint.
         */
        PersonInput: {
            /**
             * Active Name
             * @description Currently used name; optional supplementary profile basis.
             */
            active_name?: string | null;
            /**
             * As Of Date
             * Format: date
             * @description Explicit evaluation date for deterministic tests. birth_date must be <= as_of_date for a person profile.
             */
            as_of_date: string;
            /**
             * Birth Date
             * Format: date
             * @description Calendar date of birth (YYYY-MM-DD).
             */
            birth_date: string;
            /**
             * Consent Given
             * @description Whether the data subject consented to processing.
             * @default false
             */
            consent_given: boolean;
            /**
             * Core Name
             * @description Full birth name (authoritative).
             */
            core_name: string;
            /**
             * @description Normalization locale selector.
             * @default de
             */
            locale: components["schemas"]["Locale"];
        };
        /**
         * ProblemDetails
         * @description RFC-9457-style API error with a stable machine-readable code.
         */
        ProblemDetails: {
            /** Code */
            code: string;
            /** Correlation Id */
            correlation_id: string;
            /** Detail */
            detail: string;
            /**
             * Field Errors
             * @default []
             */
            field_errors: components["schemas"]["FieldError"][];
            /** Status */
            status: number;
            /** Title */
            title: string;
            /** Type */
            type: string;
        };
        /**
         * ProfileCalculationRequest
         * @description Explicit person and method policy submitted to the deterministic core.
         */
        ProfileCalculationRequest: {
            person: components["schemas"]["PersonInput"];
            policy: components["schemas"]["MethodPolicy"];
        };
        /**
         * ProfileCalculationRequestV2
         * @description Explicit person and method policy for the pythagorean-v2 endpoint.
         */
        ProfileCalculationRequestV2: {
            person: components["schemas"]["PersonInput"];
            policy: components["schemas"]["MethodPolicy"];
        };
        /**
         * ProfileCalculationResult
         * @description Complete deterministic profile contract introduced for release 0.1.4.
         */
        ProfileCalculationResult: {
            active_name?: components["schemas"]["NameNumberSet"] | null;
            attitude: components["schemas"]["NumberResult"];
            birthday: components["schemas"]["NumberResult"];
            /** @default calculation_fact */
            claim_type: components["schemas"]["ClaimType"];
            consistency: components["schemas"]["ConsistencyStatus"];
            core_name?: components["schemas"]["NameNumberSet"] | null;
            cycles: components["schemas"]["CycleCalculationResult"];
            /**
             * Deterministic Hash
             * @default
             */
            deterministic_hash: string;
            input_ref: components["schemas"]["PersonInput"];
            life_path_a: components["schemas"]["LifePathResult"];
            life_path_b: components["schemas"]["LifePathResult"];
            maturity: components["schemas"]["NumberResult"];
            /**
             * Name
             * @default complete_profile
             */
            name: string;
            policy: components["schemas"]["MethodPolicy"];
            /**
             * Schema Version
             * @default profile-calculation-result-v3
             */
            schema_version: string;
            trace: components["schemas"]["AuditTrace"];
        };
        /**
         * ProfileCalculationResultV4
         * @description Complete deterministic V2 profile contract (profile-calculation-result-v4, PR #19).
         *
         *     Uses ``NumberModel`` throughout, has explicit primary/secondary life path
         *     roles and full MethodPolicy versioning.  Additive — does not alter V1/V3.
         */
        ProfileCalculationResultV4: {
            active_name?: components["schemas"]["NameNumberSetV2"] | null;
            attitude: components["schemas"]["NumberModel"];
            birthday: components["schemas"]["NumberModel"];
            /** @default calculation_fact */
            claim_type: components["schemas"]["ClaimType"];
            core_name?: components["schemas"]["NameNumberSetV2"] | null;
            cycles: components["schemas"]["CycleCalculationResultV2"];
            /**
             * Deterministic Hash
             * @default
             */
            deterministic_hash: string;
            input_ref: components["schemas"]["PersonInput"];
            /** @description sum_all_birth_date_digits (role=primary). */
            life_path_primary: components["schemas"]["NumberModel"];
            /** @description component_then_sum (role=secondary). */
            life_path_secondary: components["schemas"]["NumberModel"];
            /**
             * Name
             * @default complete_profile_v4
             */
            name: string;
            policy: components["schemas"]["MethodPolicy"];
            /**
             * Schema Version
             * @default profile-calculation-result-v4
             */
            schema_version: string;
            trace: components["schemas"]["AuditTrace"];
        };
        /** ReadyStatus */
        ReadyStatus: {
            /**
             * Engine
             * @default ready
             * @constant
             */
            engine: "ready";
            /**
             * Provider
             * @default disabled
             * @enum {string}
             */
            provider: "disabled" | "configured";
            /**
             * Redis
             * @default not_configured
             * @enum {string}
             */
            redis: "not_configured" | "ready" | "unavailable";
            /**
             * Status
             * @default ready
             * @enum {string}
             */
            status: "ready" | "unavailable";
        };
        /**
         * ReductionOutcome
         * @description A reduced numeric result with master-number metadata.
         *
         *     ``value`` is always in ``1..9`` or one of the configured master numbers.
         *     ``intermediate`` is the pre-reduction sum (useful for the audit trace).
         *
         *     Karmic-debt detection moved OFF this primitive (Korrektur 1): the marker
         *     is only meaningful on the *methodically defined unreduced core value*
         *     of a Life Path method, not on arbitrary intermediate sums. The karmic
         *     info therefore lives on :class:`LifePathResult` (``karmic_debt``), not
         *     here. This primitive stays focused on numeric reduction + master-flag.
         */
        ReductionOutcome: {
            /**
             * Intermediate
             * @description Sum fed into the reduction.
             */
            intermediate: number;
            /**
             * Is Master
             * @description True iff value is a master number.
             * @default false
             */
            is_master: boolean;
            /**
             * Value
             * @description Reduced value (1..9 or a master number).
             */
            value: number;
        };
        /**
         * UmlautPolicy
         * @description German umlaut / semantic normalization policy (ADR 0002).
         *
         *     ``DE_DIRECT_V1`` is the V1 default for ``locale=de``. The two policies
         *     must never be mixed within a single calculation (ADR 0002 §7).
         * @enum {string}
         */
        UmlautPolicy: "de-direct-v1" | "de-expanded-v1";
        /**
         * YMode
         * @description Y classification policy (ADR 0001).
         *
         *     ``PHONETIC`` is the V1 canonical default for ``pythagorean-v1``.
         * @enum {string}
         */
        YMode: "phonetic" | "always_vowel" | "always_consonant" | "user_fixed";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    analysis_follow_up_api_v1_analyses_follow_up_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalysisFollowUpRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisFollowUp"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    analysis_report_api_v1_analyses_report_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalysisReportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisReport"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    live_api_v1_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LiveStatus"];
                };
            };
        };
    };
    ready_api_v1_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyStatus"];
                };
            };
        };
    };
    meta_api_v1_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetaResponse"];
                };
            };
        };
    };
    calculate_api_v1_profiles_calculate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileCalculationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileCalculationResult"];
                };
            };
            /** @description Calculation rejected */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    analysis_follow_up_v2_api_v2_analyses_follow_up_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalysisFollowUpRequestV2"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisFollowUpV3"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Analysis generation failed */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description LLM analysis disabled */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    analysis_report_v2_api_v2_analyses_report_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalysisReportRequestV2"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisReportV3"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Analysis generation failed */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description LLM analysis disabled */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    meta_v2_api_v2_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetaResponseV2"];
                };
            };
        };
    };
    calculate_v2_api_v2_profiles_calculate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileCalculationRequestV2"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileCalculationResultV4"];
                };
            };
            /** @description Calculation rejected */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
}
